services:
  - type: web
    name: crm-project
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn crm_project.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: crm_project.settings
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4 